#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeInWords' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. INTEGER h
#  2. INTEGER m
#
def timeInWords(h, m):
    nums = ["zero", "one", "two", "three", "four", 
            "five", "six", "seven", "eight", "nine", 
            "ten", "eleven", "twelve", "thirteen", 
            "fourteen", "fifteen", "sixteen",  
            "seventeen", "eighteen", "nineteen",  
            "twenty", "twenty one", "twenty two",  
            "twenty three", "twenty four",  
            "twenty five", "twenty six", "twenty seven", 
            "twenty eight", "twenty nine"]
        
    if m ==0:
        return nums[h] + " o' clock"
    elif m == 1:
        return nums[m]+ " minute past " + nums[h] 
    elif m == 15:
        return "quarter past " + nums[h] 
    elif m < 30:
        return nums[m]+ " minutes past " + nums[h] 
    elif m == 30:
        return "half past " + nums[h]
    elif m == 45:
        return "quarter to " +nums[h+1]
    elif m == 59:
        return nums[60-m] + " minute to " + nums[h+1]
    elif 30 <m < 60:
        return nums[60-m] + " minutes to " + nums[h+1]
            
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    h = int(input().strip())

    m = int(input().strip())

    result = timeInWords(h, m)

    fptr.write(result + '\n')

    fptr.close()
